### ISSUE TITLE
Interpolating Text

### ISSUE THREAD

**Issue by jchia** [pikajude/th-printf#9]
It appears that `%s` is for interpolating `String` and I haven't figured out how to interpolate `Text`. Is there a more convenient way besides using `unpack :: Text -> String`? If not, what about changing `st` so that it expects `Text` instead of `String` when `%s` is used? Using `unpack` to convert a `Text` to a `String` just to use with `th-printf` seems inefficient.

Maybe another way is to make an internal typeclass inhabited by both `String` and `Text` so that `%s` interpolates a value of that typeclass, but that may sometimes require explicit type annotations when used with `OverloadedStrings`.

**Comment by pikajude** [comment]
There is no native interpolating `Text` right now. The internals of this library all work directly with `String` since I'm relying on some GHC numeric show functions which also return `String`.

I can allow a new format-specifier `%t` which will just `unpack` the corresponding argument.

**Comment by peti** [comment]
That would be very much appreciated! I have recently picked up the habit of using `Text` everywhere where I used to use `String` and it's been a pretty good experience. `th-printf` is one of those few pieces that doesn't work well with `Text`, sadly.

I would also love to have a way to format to `Text` rather than `String`. I can always `pack` the result of the TH expression, of course, but that doesn't feel like a very good solution.

**Comment by pikajude** [comment]
Hi @peti and @jchia, I know it's been a VERY long span of radio silence on this repo, but I've finally had some time to work on improvements, one of which is the ability to use lazy and strict Text as format args and the ability to produce lazy Text as output.

You can use `%q` for lazy and `%Q` for strict Text. Mnemonic: capital letters sound angrier and thus more strict. I would have liked to use `%t`, but unfortunately that conflicts with the `t` width specifier.

**Comment by peti** [comment]
Those new features are not in a released version of the library yet?

**Comment by pikajude** [comment]
They're in version 0.7 which just pushed to hackage a couple days ago. https://hackage.haskell.org/package/th-printf-0.7/docs/Language-Haskell-Printf.html

**Comment by pikajude** [comment]
Closing since this feature is now available!

**Comment by peti** [comment]
Very nice, thank you!
